name: evo
channels:
  - anaconda
  - conda-forge
  - nvidia/label/cuda-12.2.2
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blast=2.12.0=pl5262h3289130_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.2=h06a4308_0
  - cuda-cccl=12.2.140=0
  - cuda-command-line-tools=12.2.2=0
  - cuda-compiler=12.2.2=0
  - cuda-cudart=12.2.140=0
  - cuda-cudart-dev=12.2.140=0
  - cuda-cudart-static=12.2.140=0
  - cuda-cuobjdump=12.2.140=0
  - cuda-cupti=12.2.142=0
  - cuda-cupti-static=12.2.142=0
  - cuda-cuxxfilt=12.2.140=0
  - cuda-documentation=12.2.140=0
  - cuda-driver-dev=12.2.140=0
  - cuda-gdb=12.2.140=0
  - cuda-libraries=12.2.2=0
  - cuda-libraries-dev=12.2.2=0
  - cuda-libraries-static=12.2.2=0
  - cuda-nsight=12.2.144=0
  - cuda-nsight-compute=12.2.2=0
  - cuda-nvcc=12.2.140=0
  - cuda-nvdisasm=12.2.140=0
  - cuda-nvml-dev=12.2.140=0
  - cuda-nvprof=12.2.142=0
  - cuda-nvprune=12.2.140=0
  - cuda-nvrtc=12.2.140=0
  - cuda-nvrtc-dev=12.2.140=0
  - cuda-nvrtc-static=12.2.140=0
  - cuda-nvtx=12.2.140=0
  - cuda-nvvp=12.2.142=0
  - cuda-opencl=12.2.140=0
  - cuda-opencl-dev=12.2.140=0
  - cuda-profiler-api=12.2.140=0
  - cuda-sanitizer-api=12.2.140=0
  - cuda-toolkit=12.2.2=0
  - cuda-tools=12.2.2=0
  - cuda-visual-tools=12.2.2=0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cudnn=8.9.2.26=cuda11_0
  - curl=7.88.1=hdbd6064_2
  - dos2unix=7.4.1=0
  - entrez-direct=16.2=he881be0_1
  - gds-tools=1.7.2.10=0
  - gettext=0.21.0=h39681ba_1
  - hmmer=3.3.2=h87f3376_2
  - icu=73.1=h6a678d5_0
  - infernal=1.1.4=h779adbc_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libcublas=12.2.5.6=0
  - libcublas-dev=12.2.5.6=0
  - libcublas-static=12.2.5.6=0
  - libcufft=11.0.8.103=0
  - libcufft-dev=11.0.8.103=0
  - libcufft-static=11.0.8.103=0
  - libcufile=1.7.2.10=0
  - libcufile-dev=1.7.2.10=0
  - libcufile-static=1.7.2.10=0
  - libcurand=10.3.3.141=0
  - libcurand-dev=10.3.3.141=0
  - libcurand-static=10.3.3.141=0
  - libcurl=7.88.1=h251f7ec_2
  - libcusolver=11.5.2.141=0
  - libcusolver-dev=11.5.2.141=0
  - libcusolver-static=11.5.2.141=0
  - libcusparse=12.1.2.141=0
  - libcusparse-dev=12.1.2.141=0
  - libcusparse-static=12.1.2.141=0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.4=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.2.1.4=0
  - libnpp-dev=12.2.1.4=0
  - libnpp-static=12.2.1.4=0
  - libnvjitlink=12.2.140=0
  - libnvjitlink-dev=12.2.140=0
  - libnvjpeg=12.2.2.4=0
  - libnvjpeg-dev=12.2.2.4=0
  - libnvjpeg-static=12.2.2.4=0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libxml2=2.10.4=hf1b16e4_1
  - mpi=1.0=openmpi
  - mpi4py=3.1.4=py311h3e5f7c9_0
  - ncurses=6.4=h6a678d5_0
  - nsight-compute=2023.2.2.3=0
  - openmpi=4.0.2=hb1b8bf9_1
  - openssl=3.0.15=h5eee18b_0
  - pcre=8.45=h295c915_0
  - perl=5.26.2=h14c3975_0
  - perl-archive-tar=2.32=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-types-serialiser=1.0=pl526_2
  - perl-xsloader=0.24=pl526_0
  - pip=23.3.1=py311h06a4308_0
  - prodigal=2.6.3=hec16e2b_4
  - python=3.11.5=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - trnascan-se=2.0.9=pl5262h779adbc_1
  - wget=1.21.4=h251f7ec_1
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.0.0
      - accelerate==0.25.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - alembic==1.13.2
      - aniso8601==9.0.1
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.2.0
      - apex==0.1
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argtyped==0.4.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - astroid==2.15.8
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrdict==2.0.1
      - attrs==23.1.0
      - autopep8==2.0.4
      - axial-positional-embedding==0.3.10
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - best-download==0.1.2
      - bioframe==0.7.2
      - biopython==1.82
      - bitsandbytes==0.42.0
      - bleach==6.2.0
      - blinker==1.8.2
      - borzoi-pytorch==0.4.0
      - boto3==1.35.69
      - botocore==1.35.69
      - cachetools==5.5.0
      - causal-conv1d==1.4.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - clang-format==17.0.6
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - colt5-attention==0.11.1
      - comm==0.2.2
      - contextlib2==21.6.0
      - contourpy==1.2.0
      - coverage==7.3.4
      - cupy-cuda111==12.3.0
      - cycler==0.12.1
      - dask==2025.1.0
      - databricks-sdk==0.32.0
      - datacache==1.4.1
      - dataproperty==1.0.1
      - datasets==2.16.0
      - debugpy==1.8.11
      - decorator==5.1.1
      - deepspeed==0.14.4
      - defusedxml==0.7.1
      - dendropy==5.0.1
      - deprecated==1.2.14
      - dill==0.3.7
      - discrete-key-value-bottleneck-pytorch==0.1.1
      - distlib==0.3.8
      - distro==1.9.0
      - dllogger==1.0.0
      - dm-tree==0.1.8
      - docker==7.1.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.15
      - dropout-layer-norm==0.1
      - einops==0.8.0
      - einx==0.3.0
      - enformer-pytorch==0.8.10
      - ete3==3.1.3
      - evaluate==0.4.1
      - evo-model==0.4
      - execnet==2.0.2
      - executing==2.0.1
      - fair-esm==2.0.0
      - fasteners==0.19
      - fastjsonschema==2.21.1
      - fastrlock==0.8.2
      - filelock==3.13.1
      - flash-attn==2.6.3
      - flask==3.0.3
      - fonttools==4.47.0
      - fqdn==1.5.1
      - frozendict==2.4.6
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - ftfy==6.1.3
      - fused-kernels==0.0.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.34.0
      - google-auth-oauthlib==0.4.6
      - graphene==3.3
      - graphql-core==3.2.4
      - graphql-relay==3.2.0
      - greenlet==3.0.3
      - grpcio==1.60.0
      - gtfparse==2.5.0
      - gunicorn==23.0.0
      - h11==0.14.0
      - h5py==3.12.1
      - hjson==3.1.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.1
      - hyper-connections==0.1.11
      - identify==2.5.33
      - idna==3.8
      - ihm==0.43
      - importlib-metadata==8.2.0
      - iniconfig==2.0.0
      - intervaltree==3.1.0
      - ipykernel==6.29.5
      - ipython==8.19.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - isort==5.13.2
      - itsdangerous==2.2.0
      - jaxtyping==0.2.25
      - jedi==0.19.1
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.3.2
      - json5==0.10.0
      - jsonlines==4.0.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.5
      - lazy-import-plus==0.0.2
      - lazy-object-proxy==1.10.0
      - lightning-utilities==0.10.0
      - llvmlite==0.44.0
      - lm-dataformat==0.0.20
      - lm-eval==0.3.0
      - local-attention==1.11.1
      - locket==1.0.0
      - lxml==4.9.4
      - mako==1.3.5
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mbstrdecoder==1.1.3
      - mccabe==0.7.0
      - mdurl==0.1.2
      - memoized-property==1.0.3
      - mistune==3.1.0
      - ml-collections==0.1.1
      - mlflow==2.16.0
      - mlflow-skinny==2.16.0
      - mock==5.1.0
      - modelcif==0.9
      - monarch-cuda==0.0.0
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - multiprocess==0.70.15
      - mypy-extensions==1.0.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nltk==3.8.1
      - nodeenv==1.8.0
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numba==0.61.0
      - numcodecs==0.13.0
      - numexpr==2.8.8
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.555.43
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - openai==1.6.1
      - openfold==1.0.1
      - opentelemetry-api==1.27.0
      - opentelemetry-sdk==1.27.0
      - opentelemetry-semantic-conventions==0.48b0
      - opt-einsum==3.3.0
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.1.4
      - pandocfilters==1.5.1
      - parso==0.8.3
      - partd==1.4.2
      - pathvalidate==3.2.0
      - peft==0.7.1
      - pexpect==4.9.0
      - pillow==10.1.0
      - platformdirs==4.2.2
      - pluggy==1.3.0
      - polars==0.20.31
      - portalocker==2.8.2
      - pre-commit==3.6.0
      - product-key-memory==0.2.11
      - progressbar33==2.4
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.43
      - protobuf==3.20.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py==1.11.0
      - py-cpuinfo==9.0.0
      - py-spy==0.3.14
      - pyarrow==14.0.2
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pybind11==2.11.1
      - pycodestyle==2.11.1
      - pycountry==23.12.11
      - pycparser==2.22
      - pydantic==1.10.17
      - pydantic-core==2.23.2
      - pyensembl==2.3.13
      - pyfaidx==0.8.1.3
      - pygments==2.17.2
      - pylint==2.17.7
      - pynndescent==0.5.13
      - pynvml==11.5.0
      - pyparsing==3.1.1
      - pytablewriter==1.2.0
      - pytest==7.4.3
      - pytest-cov==4.1.0
      - pytest-forked==1.6.0
      - pytest-xdist==3.5.0
      - python-dateutil==2.8.2
      - python-json-logger==3.2.1
      - pytorch-lightning==2.1.3
      - pytorch-triton==3.0.0+dedb7bdf33
      - pytz==2023.3.post1
      - pyvcf3==1.0.3
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - regex==2023.10.3
      - requests==2.32.3
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.0
      - rouge-score==0.1.2
      - rpds-py==0.22.3
      - rsa==4.9
      - s3transfer==0.10.4
      - sacrebleu==1.5.0
      - safetensors==0.4.1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.1
      - send2trash==1.8.3
      - sentencepiece==0.1.99
      - sentry-sdk==2.13.0
      - serializable==0.4.1
      - setproctitle==1.3.3
      - setuptools==74.1.0
      - shtab==1.7.0
      - simplejson==3.19.3
      - sinkhorn-transformer==0.11.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sqlalchemy==2.0.34
      - sqlitedict==2.1.0
      - sqlparse==0.5.1
      - stack-data==0.6.3
      - stripedhyena==0.2.2
      - stua==0.3
      - sympy==1.13.1
      - tabledata==1.3.3
      - tabulate==0.9.0
      - tcolorpy==0.1.4
      - tenacity==9.0.0
      - tensorboard==2.5.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - terminado==0.18.1
      - threadpoolctl==3.2.0
      - tinycss2==1.4.0
      - tinytimer==0.0.0
      - tokenizers==0.15.0
      - tomlkit==0.13.2
      - toolz==1.0.0
      - torch==2.5.0.dev20240814+cu121
      - torchaudio==2.4.0.dev20240814+cu121
      - torchmetrics==1.2.1
      - torchvision==0.20.0.dev20240814+cu121
      - tornado==6.4.2
      - tqdm==4.66.1
      - tqdm-multiprocess==0.0.11
      - traitlets==5.14.0
      - transformer-engine==1.10.0.dev0+aef62f4
      - transformers==4.36.2
      - triton==3.0.0
      - trl==0.7.11
      - typechecks==0.1.0
      - typeguard==2.13.3
      - typepy==1.3.2
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.9.0
      - typing-inspect==0.9.0
      - tyro==0.7.3
      - tzdata==2023.3
      - ujson==5.9.0
      - umap-learn==0.5.7
      - uri-template==1.3.0
      - urllib3==2.2.2
      - vector-quantize-pytorch==1.21.1
      - virtualenv==20.25.0
      - wandb==0.17.7
      - wandb-workspaces==0.1.8
      - wcwidth==0.2.12
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yarl==1.9.4
      - zarr==2.18.3
      - zipp==3.20.0
      - zstandard==0.22.0
prefix: /home/jwang/miniconda/envs/evo
